<a href="https://colab.research.google.com/github/raminguyen/Study-AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [8]:
#find a maximum

sales = np.array([45, 12, 89, 34, 67])
products = np.array(["Alpha", "Beta", "Gamma", "Delta",  "Epsilon"])

In [9]:
sales

array([45, 12, 89, 34, 67])

In [10]:
products

array(['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon'], dtype='<U7')

In [13]:
#1: find the index of the highest seller
top_index = np.argmax(sales)

In [14]:
top_index

np.int64(2)

In [15]:
#2: see the number in the order
sortest_sales = np.sort(sales)
sortest_sales

array([12, 34, 45, 67, 89])

In [18]:
#3: sort the product names based on their sales

sorted_indices = np.argsort(sales)

sorted_indices

array([1, 3, 0, 4, 2])

In [17]:
sorted_product_names = products[sorted_indices]
sorted_product_names

#Beta product has the lowest price.

array(['Beta', 'Delta', 'Alpha', 'Epsilon', 'Gamma'], dtype='<U7')